all:
	g++ main.cpp packet.cpp connection.cpp RNG.cpp sesskey.cpp privkey.cpp androidClient.cpp log.cpp consts.cpp AddQueue.cpp ReadQueue.cpp androidSequentions.cpp -o runConProgram -lssl -lcrypto -lpthread -lrt   
